#!/usr/bin/env python

import rospy

from sawyer_cloth_flatten.sawyer_controller import SawyerController

def main():
    rospy.init_node('sawyer_controller_node')

    sawyer_controller = SawyerController()
    rospy.on_shutdown(sawyer_controller.on_shutdown)

    rospy.spin()

if __name__ == '__main__':
    main()